name: Refactr - Run Pipeline
description: Runs a pipeline in the Refactr Platform.
branding:
  color: blue
  icon: play-circle
inputs:
  api_token:
    description: API token
    required: true
  project_id:
    description: Project ID
    required: true
  job_id:
    description: Job ID
    required: true
  variables:
    description: Variables
    required: false
  api_url:
    description: Refactr API base URL
    required: false
runs:
  using: node12
  main: dist/index.js
